version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gym-db-postgres
    restart: on-failure
    ports:
      - "5666:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym-db-postgres
    volumes:
      - gym_postgres_data:/var/lib/postgresql/data

volumes:
  gym_postgres_data:
